// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, asBinaryContentResult } from '@mux/mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import Mux from '@mux/mux-node';

export const metadata: Metadata = {
  resource: 'video.playback',
  operation: 'read',
  tags: [],
  httpMethod: 'get',
  httpPath: '/{PLAYBACK_ID}/storyboard.{EXTENSION}',
  operationId: 'get-image-storyboard',
};

export const tool: Tool = {
  name: 'storyboard_video_playback',
  description:
    'Fetch a storyboard image composed of multiple thumbnails for use in [timeline hover previews](https://docs.mux.com/guides/create-timeline-hover-previews).',
  inputSchema: {
    type: 'object',
    properties: {
      PLAYBACK_ID: {
        type: 'string',
      },
      EXTENSION: {
        type: 'string',
        enum: ['jpg', 'png', 'webp'],
      },
      asset_end_time: {
        type: 'number',
        description:
          'Set the relative end time of the asset (in seconds) when using the [instant clipping feature](https://docs.mux.com/guides/create-instant-clips).',
      },
      asset_start_time: {
        type: 'number',
        description:
          'Set the relative start time of the asset (in seconds) when using the [instant clipping feature](https://docs.mux.com/guides/create-instant-clips).',
      },
      program_end_time: {
        type: 'integer',
        description:
          'Set the end time of the asset created from a live stream when using the [instant clipping feature](https://docs.mux.com/guides/create-instant-clips). The timestamp should be provided as an epoch integer, and is compared to the program date time (PDT) generated by a live stream.',
      },
      program_start_time: {
        type: 'integer',
        description:
          'Set the start time of the asset created from a live stream when using the [instant clipping feature](https://docs.mux.com/guides/create-instant-clips). The timestamp should be provided as an epoch integer, and is compared to the program date time (PDT) generated by a live stream.',
      },
      TOKEN: {
        type: 'string',
        description:
          'Signed token (JWT) for [secure video playback](https://docs.mux.com/guides/secure-video-playback).',
      },
    },
    required: ['PLAYBACK_ID', 'EXTENSION'],
  },
  annotations: {
    readOnlyHint: true,
  },
};

export const handler = async (client: Mux, args: Record<string, unknown> | undefined) => {
  const { PLAYBACK_ID, EXTENSION, ...body } = args as any;
  return asBinaryContentResult(
    await client.video.playback.storyboard(PLAYBACK_ID, EXTENSION, body).asResponse(),
  );
};

export default { metadata, tool, handler };
